### ISSUE TITLE
关于daemon和Systemd（科普）

### ISSUE THREAD

**Issue by muzi131313** [ruanyf/node-systemd-demo#1]
Systemd相关：
https://www.zhihu.com/question/25873473   从这篇知乎上大能了解一下；
http://www.ibm.com/developerworks/cn/linux/1407_liuming_init3/   IBM上是说并发性很好，讲的是原理；
https://blog.linuxeye.com/400.html   这个是详解介绍；

daemon相关：
场景：
服务器上启动node服务有forever命令，这个是关闭远程连接，服务也会一直在；或者不用window服务器上一直开个dos窗口，或者配置开机启动node服务；
关闭node服务有如下两种方式:
1.killall node/pkill node
2.lsof -i tcp:2000
   kill -9 pid(查找到的进程pid)
原因：
forever启动的node服务，同样可以通过killall node命令给把服务给关掉
结论：
通过阮老师这个demo配置过之后，node服务就不会被这些普通的命令给kill掉了。大赞😊

ps:
1.关闭命令的帖子：http://cnodejs.org/topic/510dd169df9e9fcc581cb97f
2.kill -2与kill -9的区别：-2终止（等同ctrl+c）（mac控制台收到的命令Terminated: 15），-9强制终止（控制台：Killed: 9），详情见：http://www.xuejiehome.com/blread-1596.html
3.ps -ef | grep node：检查node命令是否存在，详情见：http://zhidao.baidu.com/link?url=c2iKGCW6q4mNTymqNkFVqJ2dqUXP1j3hWhaKwSWL2SMBr6Ch8ntgc-6TUo23S8ezEFJWA6qkhs7nbTPGQhyG-YlNkIBqZ7yvSmbMUOB2NVa
4.如果nodejs是通过supervisor命令启动，第二种方法就无效了，因为lsof -i找不到supervisor这个服务的进程，而ps -ef | grep node可以找到，不过通过这种方式找到的话，需要把supervisor和node这两个进程都给kill掉；不过，killall node最简单粗暴了；关于lsof：http://www.cnblogs.com/peida/archive/2013/02/26/2932972.html
5:因为没仔细看readme.md，这个issue就当给不了解daemon和systemd的一样的小伙伴们的说明吧，最后给阮老师造成的困扰抱歉了😂

**Comment by ruanyf** [comment]
没太看懂这个issue的意思。

个人感觉，Node还是不要跟Systemd过于耦合。

**Comment by muzi131313** [comment]
这个issue，是一开始没有太仔细看阮老师这个demo的说明，抱歉了(issue好像没法删除)。
因为看到了tcp，最近在看这个。
https://rocketeer.be/articles/deploying-node-js-with-systemd/  看完这个大概明白了。

**Comment by ruanyf** [comment]
我对Node处理TCP有兴趣，但是没研究。

最近看到这个项目，就是用tcp的。https://github.com/Fuck-You-GFW/p2pspider

**Comment by muzi131313** [comment]
p2pspider中的tcp好像是作为一个客户端去用的，https://github.com/xyfcode/zspeed  这个是作为服务端去用的；以前接触过java nio，对netty了解一点；nio太坑（主要是水平有限），涉及到粘包（客户端同一条消息发送多次）、心跳（判断服务端socket是否是假死状态）、接包（网络原因有可能一次接到半条数据）...可能还有其他的；当时没用netty，主要是对socket理解不够，出问题可能不知道怎么解决；选择用nio是说异步非阻塞，想对传统io并发的处理会好一些；现在转js开发，node这块对socket.io好像是专门对应websocket（先以http协议进行握手连接，后面的通讯使用tcp）做处理的，tcp这块好像只有net.createServer这个。websocket应用于B/S是足够，C/S上好像有点不行。现在想写一个node版本的靠谱一点的tcp的demo。
ps:一些mark:
1.nio缺陷：http://www.tuicool.com/articles/mUFnqeM
2.selector：http://www.coderli.com/netty-nio-selector/
3.nio介绍：http://www.ibm.com/developerworks/cn/education/java/j-nio/j-nio.html
4.nio模型：http://www.ibm.com/developerworks/cn/java/l-niosvr/
5.netty：http://www.infoq.com/cn/articles/netty-high-performance/
